#!/usr/bin/env python3
"""
Ducky Setup Tool

Generates a local .env file for OpenAI-backed development.

Usage:
    python ducky-setup.py --api-key YOUR_OPENAI_API_KEY
    python ducky-setup.py --api-key YOUR_OPENAI_API_KEY --model gpt-5.5
"""

import argparse
import os
import sys
from datetime import datetime


def print_status(message: str, success: bool = True) -> None:
    """Print status message with color coding."""
    prefix = "✓" if success else "✗"
    print(f"{prefix} {message}")

def backup_existing_env() -> bool:
    """
    Create backup of existing .env file if it exists.

    Returns:
        True if backup created or no file exists, False on error
    """
    if not os.path.exists('.env'):
        return True

    try:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        backup_name = f'.env.backup.{timestamp}'

        with open('.env', 'r') as src, open(backup_name, 'w') as dst:
            dst.write(src.read())

        print_status(f"Existing .env backed up to {backup_name}")
        return True

    except Exception as e:
        print_status(f"Failed to backup existing .env: {e}", False)
        return False

def write_env_file(api_key: str, model: str) -> bool:
    """
    Write .env file with Ducky configuration.

    Args:
        api_key: OpenAI API key
        model: Chat model name to use

    Returns:
        True if successful, False otherwise
    """
    try:
        env_content = f"""# Ducky Configuration - Generated by ducky-setup
# Generated: {datetime.now().isoformat()}

# OpenAI Configuration
OPENAI_API_KEY={api_key}
OPENAI_API_MODEL={model}

# Embedding Configuration
# Options: 'local' (uses sentence-transformers, free & offline)
EMBEDDING_MODE=local
LOCAL_EMBEDDING_MODEL=all-mpnet-base-v2
"""

        with open('.env', 'w') as f:
            f.write(env_content)

        print_status("Generated .env file with OpenAI configuration")
        return True

    except Exception as e:
        print_status(f"Failed to write .env file: {e}", False)
        return False

def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Ducky Setup Tool - generate .env file for OpenAI and local embeddings",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python ducky-setup.py --api-key sk-...
    python ducky-setup.py --api-key sk-... --model gpt-5.5
        """
    )

    parser.add_argument('--api-key', required=True,
                       help='OpenAI API key (required)')
    parser.add_argument('--model', default='gpt-5.5',
                       help='OpenAI chat model to use (default: gpt-5.5)')

    args = parser.parse_args()

    print("=" * 60)
    print("Ducky Setup - OpenAI Configuration".center(60))
    print("=" * 60)
    print(f"Model: {args.model}")
    print()

    # Backup existing .env file
    print("\nPreparing configuration...")
    if not backup_existing_env():
        print("\nWarning: Could not backup existing .env file. Continuing anyway...")

    # Write new .env file
    if not write_env_file(args.api_key, args.model):
        print("\nSetup failed. Could not write .env file.")
        return 1

    # Success message
    print("\n" + "=" * 60)
    print("Setup Complete!".center(60))
    print("=" * 60)
    print("✓ .env file generated with OpenAI configuration")
    print("✓ Ready to use Ducky with your OpenAI API key")
    print()
    print("Next steps:")
    print("1. Run: streamlit run 🏠_Home.py")
    print("2. Enjoy AI-powered software development assistance!")
    print()

    return 0

if __name__ == "__main__":
    sys.exit(main())
